name: Maven Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_PROJECT_PATH: calculator/pom.xml

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ./.github/workflows # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file ${{ env.MAVEN_PROJECT_PATH }}

      - name: Publish to GitHub Packages
        run: mvn deploy --file ${{ env.MAVEN_PROJECT_PATH }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
